version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"  # Expone Apache directamente en el puerto 8000
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
